name: On PRs - Linux-Ubuntu Matrix

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  Linux:
    name: 'Ubuntu 22.04 - GCC, BuildType:${{matrix.build_type}}, SHARED:${{matrix.shared_libraries}}'
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        shared_libraries: [ON, OFF]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install -y tree ninja-build
          python3 -m pip install conan lxml

      - name: Conan common config
        run: |
          conan profile detect --force

      - name: Run Conan
        run: |
          mkdir build-base_linux && cd build-base_linux
          conan install .. -s build_type=${{matrix.build_type}} -o webready=True --build missing

      - name: Build
        run: |
          cmake --preset base_linux -S . -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DBUILD_SHARED_LIBS=${{matrix.shared_libraries}}
          cmake --build build-base_linux --parallel

      - name: Install
        run: |
          cd build-base_linux
          cmake --install .

      - name: Test
        run: |
          cd build-base_linux
          ctest --output-on-failure
